list_lua_bindings = "";
list_lua_bindings+="imgui_begin\n";
lua_register(lstate, "imgui_begin", imgui_begin);
list_lua_bindings+="imgui_end\n";
lua_register(lstate, "imgui_end", imgui_end);
list_lua_bindings+="imgui_button\n";
lua_register(lstate, "imgui_button", imgui_button);
list_lua_bindings+="imgui_text\n";
lua_register(lstate, "imgui_text", imgui_text);
list_lua_bindings+="imgui_textwrapped\n";
lua_register(lstate, "imgui_textwrapped", imgui_textwrapped);
list_lua_bindings+="imgui_sliderint\n";
lua_register(lstate, "imgui_sliderint", imgui_sliderint);
list_lua_bindings+="imgui_sliderfloat\n";
lua_register(lstate, "imgui_sliderfloat", imgui_sliderfloat);
list_lua_bindings+="imgui_sliderfloat2\n";
lua_register(lstate, "imgui_sliderfloat2", imgui_sliderfloat2);
list_lua_bindings+="imgui_sliderfloat3\n";
lua_register(lstate, "imgui_sliderfloat3", imgui_sliderfloat3);
list_lua_bindings+="imgui_sliderfloat4\n";
lua_register(lstate, "imgui_sliderfloat4", imgui_sliderfloat4);
list_lua_bindings+="imgui_dragfloat\n";
lua_register(lstate, "imgui_dragfloat", imgui_dragfloat);
list_lua_bindings+="imgui_dragfloat2\n";
lua_register(lstate, "imgui_dragfloat2", imgui_dragfloat2);
list_lua_bindings+="imgui_dragfloat3\n";
lua_register(lstate, "imgui_dragfloat3", imgui_dragfloat3);
list_lua_bindings+="imgui_dragfloat4\n";
lua_register(lstate, "imgui_dragfloat4", imgui_dragfloat4);
list_lua_bindings+="imgui_checkbox\n";
lua_register(lstate, "imgui_checkbox", imgui_checkbox);
list_lua_bindings+="imgui_sameline\n";
lua_register(lstate, "imgui_sameline", imgui_sameline);
list_lua_bindings+="imgui_newline\n";
lua_register(lstate, "imgui_newline", imgui_newline);
list_lua_bindings+="imgui_spacing\n";
lua_register(lstate, "imgui_spacing", imgui_spacing);
list_lua_bindings+="imgui_setnextwindowsize\n";
lua_register(lstate, "imgui_setnextwindowsize", imgui_setnextwindowsize);
list_lua_bindings+="imgui_progressbar\n";
lua_register(lstate, "imgui_progressbar", imgui_progressbar);
list_lua_bindings+="imgui_treenode\n";
lua_register(lstate, "imgui_treenode", imgui_treenode);
list_lua_bindings+="imgui_treepop\n";
lua_register(lstate, "imgui_treepop", imgui_treepop);
list_lua_bindings+="imgui_image_rendertarget2D\n";
lua_register(lstate, "imgui_image_rendertarget2D", imgui_image_rendertarget2D);
list_lua_bindings+="imgui_image_renderdepth2D\n";
lua_register(lstate, "imgui_image_renderdepth2D", imgui_image_renderdepth2D);
list_lua_bindings+="create_rendertarget2D\n";
lua_register(lstate, "create_rendertarget2D", create_rendertarget2D);
list_lua_bindings+="create_empty_rendertarget2D\n";
lua_register(lstate, "create_empty_rendertarget2D", create_empty_rendertarget2D);
list_lua_bindings+="destroy_rendertarget2D\n";
lua_register(lstate, "destroy_rendertarget2D", destroy_rendertarget2D);
list_lua_bindings+="attach_srv_rendertarget2D\n";
lua_register(lstate, "attach_srv_rendertarget2D", attach_srv_rendertarget2D);
list_lua_bindings+="attach_uav_rendertarget2D\n";
lua_register(lstate, "attach_uav_rendertarget2D", attach_uav_rendertarget2D);
list_lua_bindings+="set_rendertarget_rendertarget2D\n";
lua_register(lstate, "set_rendertarget_rendertarget2D", set_rendertarget_rendertarget2D);
list_lua_bindings+="set_rendertarget_and_depth_rendertarget2D\n";
lua_register(lstate, "set_rendertarget_and_depth_rendertarget2D", set_rendertarget_and_depth_rendertarget2D);
list_lua_bindings+="clear_rendertarget_rendertarget2D\n";
lua_register(lstate, "clear_rendertarget_rendertarget2D", clear_rendertarget_rendertarget2D);
list_lua_bindings+="copy_resource_rendertarget2D\n";
lua_register(lstate, "copy_resource_rendertarget2D", copy_resource_rendertarget2D);
list_lua_bindings+="create_rendertarget3D\n";
lua_register(lstate, "create_rendertarget3D", create_rendertarget3D);
list_lua_bindings+="create_empty_rendertarget3D\n";
lua_register(lstate, "create_empty_rendertarget3D", create_empty_rendertarget3D);
list_lua_bindings+="destroy_rendertarget3D\n";
lua_register(lstate, "destroy_rendertarget3D", destroy_rendertarget3D);
list_lua_bindings+="attach_srv_rendertarget3D\n";
lua_register(lstate, "attach_srv_rendertarget3D", attach_srv_rendertarget3D);
list_lua_bindings+="attach_uav_rendertarget3D\n";
lua_register(lstate, "attach_uav_rendertarget3D", attach_uav_rendertarget3D);
list_lua_bindings+="clear_rendertarget_rendertarget3D\n";
lua_register(lstate, "clear_rendertarget_rendertarget3D", clear_rendertarget_rendertarget3D);
list_lua_bindings+="copy_resource_rendertarget3D\n";
lua_register(lstate, "copy_resource_rendertarget3D", copy_resource_rendertarget3D);
list_lua_bindings+="set_rendertarget_backbuffer\n";
lua_register(lstate, "set_rendertarget_backbuffer", set_rendertarget_backbuffer);
list_lua_bindings+="set_rendertarget_and_depth_backbuffer\n";
lua_register(lstate, "set_rendertarget_and_depth_backbuffer", set_rendertarget_and_depth_backbuffer);
list_lua_bindings+="set_rendertarget_and_depthmain_backbuffer\n";
lua_register(lstate, "set_rendertarget_and_depthmain_backbuffer", set_rendertarget_and_depthmain_backbuffer);
list_lua_bindings+="clear_rendertarget_backbuffer\n";
lua_register(lstate, "clear_rendertarget_backbuffer", clear_rendertarget_backbuffer);
list_lua_bindings+="attach_srv_depthmain\n";
lua_register(lstate, "attach_srv_depthmain", attach_srv_depthmain);
list_lua_bindings+="clear_depth_depthmain\n";
lua_register(lstate, "clear_depth_depthmain", clear_depth_depthmain);
list_lua_bindings+="set_depth_depthmain\n";
lua_register(lstate, "set_depth_depthmain", set_depth_depthmain);
list_lua_bindings+="create_renderdepth2D\n";
lua_register(lstate, "create_renderdepth2D", create_renderdepth2D);
list_lua_bindings+="destroy_renderdepth2D\n";
lua_register(lstate, "destroy_renderdepth2D", destroy_renderdepth2D);
list_lua_bindings+="attach_srv_renderdepth2D\n";
lua_register(lstate, "attach_srv_renderdepth2D", attach_srv_renderdepth2D);
list_lua_bindings+="clear_depth_renderdepth2D\n";
lua_register(lstate, "clear_depth_renderdepth2D", clear_depth_renderdepth2D);
list_lua_bindings+="set_depth_renderdepth2D\n";
lua_register(lstate, "set_depth_renderdepth2D", set_depth_renderdepth2D);
list_lua_bindings+="create_buffer\n";
lua_register(lstate, "create_buffer", create_buffer);
list_lua_bindings+="destroy_buffer\n";
lua_register(lstate, "destroy_buffer", destroy_buffer);
list_lua_bindings+="attach_srv_buffer\n";
lua_register(lstate, "attach_srv_buffer", attach_srv_buffer);
list_lua_bindings+="attach_uav_buffer\n";
lua_register(lstate, "attach_uav_buffer", attach_uav_buffer);
list_lua_bindings+="create_fx\n";
lua_register(lstate, "create_fx", create_fx);
list_lua_bindings+="destroy_fx\n";
lua_register(lstate, "destroy_fx", destroy_fx);
list_lua_bindings+="use_fx\n";
lua_register(lstate, "use_fx", use_fx);
list_lua_bindings+="create_computefx\n";
lua_register(lstate, "create_computefx", create_computefx);
list_lua_bindings+="destroy_computefx\n";
lua_register(lstate, "destroy_computefx", destroy_computefx);
list_lua_bindings+="use_computefx\n";
lua_register(lstate, "use_computefx", use_computefx);
list_lua_bindings+="dispatch_computefx\n";
lua_register(lstate, "dispatch_computefx", dispatch_computefx);
list_lua_bindings+="use_viewport\n";
lua_register(lstate, "use_viewport", use_viewport);
list_lua_bindings+="use_rasterizer\n";
lua_register(lstate, "use_rasterizer", use_rasterizer);
list_lua_bindings+="use_nocull_rasterizer\n";
lua_register(lstate, "use_nocull_rasterizer", use_nocull_rasterizer);
list_lua_bindings+="use_wireframe_rasterizer\n";
lua_register(lstate, "use_wireframe_rasterizer", use_wireframe_rasterizer);
list_lua_bindings+="use_alphablending\n";
lua_register(lstate, "use_alphablending", use_alphablending);
list_lua_bindings+="clear_alphablending\n";
lua_register(lstate, "clear_alphablending", clear_alphablending);
list_lua_bindings+="use_nowrite_depthstencil\n";
lua_register(lstate, "use_nowrite_depthstencil", use_nowrite_depthstencil);
list_lua_bindings+="use_write_depthstencil\n";
lua_register(lstate, "use_write_depthstencil", use_write_depthstencil);
list_lua_bindings+="clear_depthstencil\n";
lua_register(lstate, "clear_depthstencil", clear_depthstencil);
list_lua_bindings+="use_cube\n";
lua_register(lstate, "use_cube", use_cube);
list_lua_bindings+="use_quad\n";
lua_register(lstate, "use_quad", use_quad);
list_lua_bindings+="use_sphere\n";
lua_register(lstate, "use_sphere", use_sphere);
list_lua_bindings+="draw_cube\n";
lua_register(lstate, "draw_cube", draw_cube);
list_lua_bindings+="draw_sphere\n";
lua_register(lstate, "draw_sphere", draw_sphere);
list_lua_bindings+="draw_quad\n";
lua_register(lstate, "draw_quad", draw_quad);
list_lua_bindings+="draw_instances_quad\n";
lua_register(lstate, "draw_instances_quad", draw_instances_quad);
list_lua_bindings+="draw_instances_sphere\n";
lua_register(lstate, "draw_instances_sphere", draw_instances_sphere);
list_lua_bindings+="draw_instances_cube\n";
lua_register(lstate, "draw_instances_cube", draw_instances_cube);
list_lua_bindings+="emit_vertex\n";
lua_register(lstate, "emit_vertex", emit_vertex);
list_lua_bindings+="get_window_size\n";
lua_register(lstate, "get_window_size", get_window_size);
list_lua_bindings+="get_time\n";
lua_register(lstate, "get_time", get_time);
list_lua_bindings+="get_delta_time\n";
lua_register(lstate, "get_delta_time", get_delta_time);
list_lua_bindings+="set_camera\n";
lua_register(lstate, "set_camera", set_camera);
list_lua_bindings+="set_light_camera\n";
lua_register(lstate, "set_light_camera", set_light_camera);
list_lua_bindings+="set_perspective\n";
lua_register(lstate, "set_perspective", set_perspective);
list_lua_bindings+="set_orthographic\n";
lua_register(lstate, "set_orthographic", set_orthographic);
list_lua_bindings+="set_light_perspective\n";
lua_register(lstate, "set_light_perspective", set_light_perspective);
list_lua_bindings+="set_light_orthographic\n";
lua_register(lstate, "set_light_orthographic", set_light_orthographic);
list_lua_bindings+="create_particle_buffer\n";
lua_register(lstate, "create_particle_buffer", create_particle_buffer);
list_lua_bindings+="clean_srv\n";
lua_register(lstate, "clean_srv", clean_srv);
list_lua_bindings+="clean_uav\n";
lua_register(lstate, "clean_uav", clean_uav);
list_lua_bindings+="set_translation_transform\n";
lua_register(lstate, "set_translation_transform", set_translation_transform);
list_lua_bindings+="get_translation_transform\n";
lua_register(lstate, "get_translation_transform", get_translation_transform);
list_lua_bindings+="set_scale_transform\n";
lua_register(lstate, "set_scale_transform", set_scale_transform);
list_lua_bindings+="get_scale_transform\n";
lua_register(lstate, "get_scale_transform", get_scale_transform);
list_lua_bindings+="set_rotation_transform\n";
lua_register(lstate, "set_rotation_transform", set_rotation_transform);
list_lua_bindings+="get_rotation_transform\n";
lua_register(lstate, "get_rotation_transform", get_rotation_transform);
list_lua_bindings+="set_customdata\n";
lua_register(lstate, "set_customdata", set_customdata);
list_lua_bindings+="get_customdata\n";
lua_register(lstate, "get_customdata", get_customdata);
list_lua_bindings+="update_globalconstantbuffer\n";
lua_register(lstate, "update_globalconstantbuffer", update_globalconstantbuffer);
list_lua_bindings+="update_transformbuffer\n";
lua_register(lstate, "update_transformbuffer", update_transformbuffer);
list_lua_bindings+="update_customdatabuffer\n";
lua_register(lstate, "update_customdatabuffer", update_customdatabuffer);
